-- =============================================================================
-- Vínculo HR SaaS — Multi-tenant (entorno local / pruebas)
-- Ejecutar en: Supabase Dashboard → SQL Editor → Run
--
-- Idempotente: usa IF NOT EXISTS y comprueba la FK antes de crearla.
-- Seguro con datos existentes: organization_id se añade como nullable.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 1. Tabla organizations (tenant raíz)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.organizations (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.organizations IS
  '[Multi-tenant] Organización cliente del SaaS de RRHH. Raíz de aislamiento de datos.';

COMMENT ON COLUMN public.organizations.id IS
  'int8 autoincremental (IDENTITY). Identificador único del tenant.';

COMMENT ON COLUMN public.organizations.name IS
  'Nombre visible de la organización.';

COMMENT ON COLUMN public.organizations.created_at IS
  'Fecha de alta del tenant en la plataforma.';

-- -----------------------------------------------------------------------------
-- 2. Columna organization_id en groups
-- -----------------------------------------------------------------------------
ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS organization_id BIGINT;

COMMENT ON COLUMN public.groups.organization_id IS
  '[Multi-tenant] FK al tenant propietario del equipo. ON DELETE CASCADE.';

-- -----------------------------------------------------------------------------
-- 3. Foreign Key → organizations(id) ON DELETE CASCADE
-- -----------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'groups_organization_id_fkey'
      AND conrelid = 'public.groups'::regclass
  ) THEN
    ALTER TABLE public.groups
      ADD CONSTRAINT groups_organization_id_fkey
      FOREIGN KEY (organization_id)
      REFERENCES public.organizations (id)
      ON DELETE CASCADE;
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 4. Índice para filtrar equipos por organización
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_groups_organization_id
  ON public.groups (organization_id);

COMMIT;

-- =============================================================================
-- Opcional — seed local (descomenta si quieres una org de prueba al instante)
-- =============================================================================
-- INSERT INTO public.organizations (name)
-- VALUES ('Organización de prueba (local)')
-- RETURNING id, name, created_at;
